# -*- coding: utf-8 -*-
"""MarkovChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Xk9YFHfrnpslQSxhAxVd52tztTlFT29

This workbook includes some code to organize and generate phrases to be used as parent sequences for the evolutionary algorithm.

Below are the starting states to be used in our layers:

| State | Layer      | Two 5-counts                                               |
|-------|------------|------------------------------------------------------------|
| A     | top bun    | Basic + cross front into slice                             |
| B     | bottom bun | Cross behind bicycle + bicycle stomp stomp                 |
| C     | top bun    | Basic + bicycle and slices                                 |
| D     | burger     | Step together step + dancing in shoes (x2)                 |
| E     | burger     | Cross behind step + cross step (x2)                        |
| F     | burger     | Second half of A phrase                                    |
| G     | top bun    | First half of A phrase                                     |
| H     | burger     | Cross behind bicycle (x2)                                  |
| I     | burger     | Cross front jump together cross back (x2)                  |
| J     | bottom bun | Cross behind + in shoes + bicycle stomp stomp              |
| K     | bottom bun | Basic + cross behind jump together stomp stomp (same foot) |

Our layers include our first layer (top bun) + middle layers (top bun or burger, repeated twice)+ last layer (bottom bun). Our generated sequence will be of length 4.

First let's define our states.
"""

import random

states = {
    'A': {'layer': 'top bun', 'phrase': 'Basic + cross front into slice', 'weight': 1},
    'B': {'layer': 'bottom bun', 'phrase': 'Cross behind bicycle + bicycle stomp stomp', 'weight': 1},
    'C': {'layer': 'top bun', 'phrase': 'Basic + bicycle and slices', 'weight': 1},
    'D': {'layer': 'burger', 'phrase': 'Step together step + dancing in shoes (x2)', 'weight': 1},
    'E': {'layer': 'burger', 'phrase': 'Cross behind step + cross step (x2)', 'weight': 1},
    'F': {'layer': 'burger', 'phrase': 'Second half of A phrase', 'weight': 1},
    'G': {'layer': 'top bun', 'phrase': 'First half of A phrase', 'weight': 1},
    'H': {'layer': 'burger', 'phrase': 'Cross behind bicycle (x2)', 'weight': 1},
    'I': {'layer': 'burger', 'phrase': 'Cross front jump together cross back (x2)', 'weight': 1},
    'J': {'layer': 'bottom bun', 'phrase': 'Cross behind + in shoes + bicycle stomp stomp', 'weight': 1},
    'K': {'layer': 'bottom bun', 'phrase': 'Basic + cross behind jump together stomp stomp (same foot)', 'weight': 1}
}

layers = {
    'top bun': ['A', 'C', 'G'],
    'burger': ['D', 'E', 'F', 'H', 'I'],
    'bottom bun': ['B', 'J', 'K'],
    'ingredient': []
}

# combine top bun and burger states for middle layers
layers['ingredient'] = layers['top bun'] + layers['burger']

"""Next, let's build out a few functions.

The first function `select_state` will take in one of our three layers (top bun, bottom bun, ingredients) and pick a random state from that layer.
We added a weight value to the state dictionary to allow for weights with higher values to be more likely to be chosen (this implementation sort of works)

The second function `generate_sequence` will build out a phrase (our "burger") with a top bun, bottom bun, and filling layers (in multiples of two). The default is to build a phrase with 4 2-counts (giving an 8 count phrase).

The last function `stage_directions` is used to translate the phrase into dance directions by referencing the state's description in the state dictionary.
"""

#randomly selects based off weight (1 default, 2 more likely, 3 most likely)

def select_state(layer_name):
    states_in_layer = layers[layer_name]
    weights = [states[s]['weight'] for s in states_in_layer]
    return random.choices(states_in_layer, weights=weights, k=1)[0]

def generate_sequence(sequence_length=4, filling_times=1):
    """
    sequence_length: total layers in sequence
    filling_times: how many times to add a random ingredient in the middle layers
    """
    sequence = []

    #grab a top bun (state 0)
    sequence.append(select_state('top bun'))

    #fill middle layers (state 1 and state 2)
    middle_layers_count = sequence_length - 2
    for _ in range(middle_layers_count):
        for _ in range(filling_times):
            sequence.append(select_state('ingredient'))

    #end with a bottom bun (state 3)
    sequence.append(select_state('bottom bun'))

    return sequence

def stage_directions(sequence):
    return [states[s]['phrase'] for s in sequence]

"""Press the button below to generate!"""

seq_length = 4
filling = 1

generated_sequence = generate_sequence(sequence_length=seq_length, filling_times=filling)
print("Generated state sequence:", generated_sequence)
print("Corresponding states:")
for phrase in stage_directions(generated_sequence):
  print("-", phrase)

"""Then let's mutate randomly!"""

def update(seq):
  rand = random.randint(0,20)
  if rand <= 2:
    old = seq[0]
    seq[0] = select_state('top bun')
    new = seq[0]
  elif  rand <= 10:
    old = seq[1]
    seq[1] = select_state('burger')
    new = seq[1]
  elif rand <= 18:
    old = seq[2]
    seq[2] = select_state('burger')
    new = seq[2]
  else:
    old = seq[3]
    seq[3] = select_state("bottom bun")
    new = seq[3]
  print("Changing the state", old, "to", new)

#random.seed(42)
#generated_sequence = generate_sequence(sequence_length=seq_length, filling_times=filling)
#generated_sequence = ["C", "F", "E", "K"]
print(generated_sequence)
update(generated_sequence)
print(generated_sequence)
print("Corresponding states:")
for phrase in stage_directions(generated_sequence):
  print("-", phrase)

"""The code above will generate a specific length sequence using markov priniciples, but is only generating a single phrase.

Let's add some functions below that will implement our evolutionary algorithm.
"""

#fill this out

"""Below is some code to create mermaid diagram."""

# Commented out IPython magic to ensure Python compatibility.
# %%html
# 
# flowchart LR
#     %% Layer 1
#     subgraph L1["Layer 1: Top Bun"]
#         A1[A]
#         C1[C]
#         G1[G]
#     end
# 
#     %% Layer 2
#     subgraph L2["Layer 2: Middle"]
#         A2[A]
#         C2[C]
#         G2[G]
#         D2[D]
#         E2[E]
#         F2[F]
#         H2[H]
#         I2[I]
#     end
# 
#     %% Layer 3
#     subgraph L3["Layer 3: Middle (repeat)"]
#         A3[A]
#         C3[C]
#         G3[G]
#         D3[D]
#         E3[E]
#         F3[F]
#         H3[H]
#         I3[I]
#     end
# 
#     %% Layer 4
#     subgraph L4["Layer 4: Bottom Bun"]
#         B4[B]
#         J4[J]
#         K4[K]
#     end